global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "Prometheus Server"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"] # Prometheus Server
  - job_name: "Golang App"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["golang-app:8080"] # Golang app
  - job_name: "Nodejs App"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["nodejs-app:8081"] # Nodejs app
