{
 "title": "Go Metrics Official",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "2023-03-31T03:16:54.204Z", "to": "2023-03-31T03:22:45.547Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines, instance)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "% CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\"}[$interval])",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  }
 ]
}