{
 "title": "Nodejs Metrics Official",
 "description": "Nodejs runtime metrics",
 "time": { "from": "2023-03-31T03:24:44.185Z", "to": "2023-03-31T03:32:47.432Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nodejs_active_handles, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "% CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\"}[$interval])",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} External Memory"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Event Loop Lag"
    }
   ]
  }
 ]
}